# Generated by Django 5.0.4 on 2024-06-05 07:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newapp", "0007_rename_name_newsletter_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="customers",
            new_name="Customer",
        ),
        migrations.RenameModel(
            old_name="OrderItems",
            new_name="OrderItem",
        ),
    ]
