# Generated by Django 5.0.4 on 2024-06-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newapp", "0008_rename_customers_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=100, null=True)),
                ("lastname", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("message", models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
